from src.enum.operacao import Operacao

PROB_CROSSOVER = 0.8
PROB_MUTACAO = 0.1
PROB_REPRODUCAO = 0.1

OP_PROB = {
    Operacao.CROSSOVER: PROB_CROSSOVER,
    Operacao.MUTACAO: PROB_MUTACAO,
    Operacao.REPRODUCAO: PROB_REPRODUCAO,
}
